<div>
    <div class="container py-10">
        <div>
            <h1 class="text-[#3E3C4F] text-xl leading-none mb-3 uppercase">Políticas de privacidad</h1>
            <p><b>INTRODUCCIÓN</b></p>
            <p>La presente "Política de Privacidad" que regula el tratamiento de los datos personales, se aplica a los datos personales que Cien Pies Producciones SAC, identificado con RUC N° 20515831160 y domicilio en Calle Alfredo Salazar 750 – San Isidro, procesa y recopila de los Usuarios que contratan sus servicios y los que se registran en el sitio Web a través de su Plataforma Digital.</p>
            <p>Cien Pies Producciones SAC asegura la máxima reserva y protección de aquellos datos personales de los Usuarios del sitio en Internet de su propiedad, que ingresen al referido sitio Web.</p>
            <p><b>OBJETIVO Y FINALIDAD</b></p>
            <p>En nuestra empresa somos conscientes de la elevada consideración que tiene la privacidad de nuestros Clientes y de todas aquellas personas que se interesan por nuestros productos y servicios. Siendo consecuentes con esta consideración tenemos el compromiso de respetar su privacidad y proteger la confidencialidad de su información privada y datos personales. Y es por ello que el objetivo de esta política de privacidad es dar a conocer a nuestros Usuarios la manera en que se recopilan, se tratan y se protegen los datos personales que a través de Internet son introducidos en el sitio Web a su disposición.</p>
            <p>La información personal privada no incluye información que está disponible a través de fuentes accesibles al público, es decir, de medios de comunicación electrónica, óptica y de otra tecnología concebidos para facilitar información al público y abiertos a la consulta general, como son: las guías telefónicas, los diarios y revistas, los medios de comunicación social, las listas profesionales, los repertorios de jurisprudencia anonimizados, los Registros Públicos administrados por la Superintendencia Nacional de Registros Públicos, Registro nacional de identificación y estado civil - RENIEC, así como todo otro registro o banco de datos calificado como público conforme a ley, y la información que ostentan las entidades de la Administración Pública y que deba ser entregada a los administrados en aplicación de la Ley Nº 27806 - Ley de Transparencia y Acceso a la Información Pública.</p>
            <p>Estamos especialmente interesados en ofrecer a nuestros Usuarios el más alto nivel de seguridad y proteger la confidencialidad de los datos que nos aporta. Por ello, las transacciones comerciales son realizadas en un entorno de servidor seguro bajo protocolo SSL (Secure Socket Layer), actualmente empleado por las empresas más importantes del mundo para realizar transacciones electrónicas seguras.</p>
            <p>El sitio Web ha sido creado y diseñado con la finalidad que realice ofertas de bienes y servicios, así como facilitar otro tipo de información que creemos puede ser de interés y crear así un espacio de comunicación para los Usuarios.</p>
            <p><b>LEGISLACIÓN</b></p>
            <p>Esta política está regulada por la legislación peruana y en particular por Ley N° 29733 - Ley de Protección de Datos Personales, modificada por el Decreto Legislativo 1353, Decreto Supremo N° 003-2013-JUS, Reglamento de la Ley N° 29733. Directiva de Seguridad de la Información, aprobada por la Resolución Directoral N° 019-2013-JUS/DGPDP.</p>
            <p>De acuerdo con la Ley N° 29733 - Ley de Protección de Datos Personales, modificada por el Decreto Legislativo 1353, y su Reglamento aprobado por el Decreto Supremo N° 003-2013-JUS, se entiende por datos personales toda información numérica, alfabética, gráfica, fotográfica, acústica, sobre hábitos personales, o de cualquier otro tipo concerniente a una persona natural que la identifica o la hace identificable a través de medios que pueden ser razonablemente utilizados.</p>
            <p>Asimismo, se entiende por Tratamiento de Datos Personales a cualquier operación o procedimiento técnico, automatizado o no, que permite la recopilación, registro, organización, almacenamiento, conservación, elaboración, modificación, extracción, consulta, utilización, bloqueo, supresión, comunicación por transferencia o por difusión o cualquier otra forma de procesamiento que facilite el acceso, correlación o interconexión de los datos personales.</p>
            <p>I. Cien Pies Producciones SAC desarrolla su política de tratamiento de datos personales en atención a los principios rectores establecidos en la Ley Nº 29733 - Ley de Protección de Datos Personales modificada por el Decreto Legislativo 1353 y por lo tanto:
            <ol>
                <li>De acuerdo al principio de legalidad, rechaza la recopilación de los datos personales de nuestros Usuarios por medios fraudulentos, desleales o ilícitos.</li>
                <li>Conforme al principio de consentimiento, en el tratamiento de los datos personales de nuestros Usuarios mediará su consentimiento.</li>
            </ol>
            <p>II. Los datos personales de nuestros Usuarios se recopilarán para una finalidad determinada, explícita y lícita, y no se extenderá a otra finalidad que no haya sido la establecida de manera inequívoca como tal al momento de su recopilación, excluyendo los casos de actividades de valor histórico, estadístico o científico cuando se utilice un procedimiento de disociación o anonimización.</p>
            <ol>
                <li>Todo tratamiento de datos personales de nuestros Usuarios será adecuado, relevante y no excesivo a la finalidad para la que estos hubiesen sido recopilados.</li>
                <li>Los datos personales que vayan a ser tratados serán veraces, exactos y, en la medida de lo posible, actualizados, necesarios, pertinentes y adecuados respecto de la finalidad para la que fueron recopilados. Se conservarán de forma tal que se garantice su seguridad y solo por el tiempo necesario para cumplir con la finalidad del tratamiento.</li>
                <li>Cien Pies Producciones SAC y, en su caso, los encargados de tratamiento, adoptan las medidas técnicas, organizativas y legales necesarias para garantizar la seguridad y confidencialidad de los datos personales.</li>
            </ol>
            <p>III. Cien Pies Producciones SAC informa a sus Usuarios que pueden ejercer sus derechos contenidos en el derecho constitucional a la protección de datos personales en sede administrativa ante la Autoridad Nacional de Protección de Datos y en sede jurisdiccional ante el Poder Judicial a los efectos del inicio del correspondiente proceso de habeas data.</p>
            <p>IV. Cien Pies Producciones SAC garantiza el nivel adecuado de protección de los datos personales de sus Usuarios para el flujo transfronterizo de datos personales, con un mínimo de protección equiparable a lo previsto por la Ley Nº 29733 o por los estándares internacionales de la materia.</p>
            <p><b>INFORMACIÓN</b></p>
            <p>Se informa a los Usuarios que los datos personales que introduzcan en los formularios que se encuentran en la opción "Registro" de la Plataforma Digital serán tratados por Cien Pies Producciones SAC para poder gestionar los comentarios que nos hagan en éstos y para poder interactuar con estos Usuarios, y se regirán por lo expuesto en esta Política de Privacidad y por las condiciones expuestas en el mismo formulario.</p>
            <p><b>CALIDAD DE LOS DATOS PERSONALES</b></p>
            <p>Los datos personales solicitados a los Usuarios, son datos básicos de contacto y son adecuados, pertinentes y no excesivos en relación con la finalidad para los que se recogen. Los datos personales a  los que Cien Pies Producciones SAC tendrá acceso, serán aquellos que el Usuario facilite voluntariamente rellenando los formularios puestos para tal efecto.</p>
            <p>Cien Pies Producciones SAC les proporciona a sus Usuarios los recursos técnicos adecuados para que tomen conocimiento de la presente Política de Privacidad y de cualquier otra información que pueda ser relevante; constituyendo el ingreso de Datos Personales o información confidencial en el sitio Web, la manifestación expresa de su consentimiento a la presente Política de Privacidad.</p>
            <p>Los datos personales facilitados por los Usuarios tienen que ser exactos y correctos de forma que respondan con veracidad a su situación actual. En caso contrario estos datos serán cancelados. Los datos personales facilitados por los Usuarios son recopilados para el cumplimiento de las finalidades expuestas en este documento y no se usarán para otras finalidades incompatibles con las especificadas.</p>
            <p>Los datos personales serán cancelados cuando hayan dejado de ser necesarios para las finalidades para las cuales han sido recopilados. Sin embargo, se conservarán durante el tiempo en que pueda exigirse algún tipo de responsabilidad a Cien Pies Producciones SAC derivada de esta relación con los Usuarios, es decir, por 2 años contando desde la finalización del último encargo realizado, en cumplimiento al artículo 36 del reglamento de la ley 29733.</p>
            <p><b>FINALIDAD DE LOS TRATAMIENTOS DE LA INFORMACIÓN PERSONAL</b></p>
            <p>Las finalidades de tratamiento de los datos personales que los Usuarios introducen en los diferentes formularios de la Plataforma Digital son para poder dar contestación a las consultas, peticiones y otro tipo de información que nos realicen a través de éstos.</p>
        </div>
    </div>
</div>
